/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckableTag: typeof import('ant-design-vue/es')['CheckableTag']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
  }
}
